packages:
  - 'packages/*'
  - 'apps/*'
  - 'docs'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

catalog:
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/circle-flags': ^1.2.5
  '@nuxt/eslint-config': ^1.15.2
  '@nuxtjs/i18n': ^10.4.0
  eslint: ^10.7.0
  appwrite: ^26.0.0
  node-appwrite: ^26.2.0
  '@types/node': ^22.18.0
  nuxt: ^4.4.8
  '@nuxt/ui': ^4.10.0
  '@nuxtjs/mdc': ^0.22.2
  '@pinia/nuxt': ^0.11.3
  pinia: ^3.0.4
  vue: ^3.5.38
  typescript: ^5.9.3
  vitest: ^4.1.8
  vue-tsc: ^3.3.8
  zod: ^4.4.3
  jiti: ^2.7.0
  nodemailer: ^7.0.0
  ioredis: ^5.9.0
  '@types/nodemailer': ^7.0.0
  stripe: ^18.0.0
  '@playwright/test': ^1.50.0
