// GENERIERT von scripts/generate-themes.ts aus theme.catalog.ts — nicht von Hand editieren.
// Handgepflegt bleiben: default-Eintrag, NEUTRAL_REGISTRY, Typen (themeRegistry.ts).
import type { MauiTheme } from './themeRegistry'

export const GENERATED_THEMES: MauiTheme[] = [
  { id: 'crimson', name: 'Crimson', file: '/themes/crimson.css', color: '#ff2357', variants: [
    { id: 'soft', color: '#d36871' },
    { id: 'muted', color: '#b97a7d' },
    { id: 'vivid', color: '#ef004c' },
    { id: 'deep', color: '#d00041' },
    { id: 'bright', color: '#ff7280' },
    { id: 'warm', color: '#fa3e00' },
    { id: 'cool', color: '#f7258c' },
    { id: 'dawn', color: '#f545c7' },
    { id: 'dusk', color: '#be5d00' },
    { id: 'pastel', color: '#ea8f94' },
  ] },
  { id: 'coral', name: 'Coral', file: '/themes/coral.css', color: '#ef5a3d', variants: [
    { id: 'soft', color: '#ca7968' },
    { id: 'muted', color: '#b4857a' },
    { id: 'vivid', color: '#f03200' },
    { id: 'deep', color: '#cc3719' },
    { id: 'bright', color: '#ff8066' },
    { id: 'warm', color: '#e16c00' },
    { id: 'cool', color: '#ef546c' },
    { id: 'dawn', color: '#f662a0' },
    { id: 'dusk', color: '#b26f00' },
    { id: 'pastel', color: '#e29d8e' },
  ] },
  { id: 'sunset', name: 'Sunset', file: '/themes/sunset.css', color: '#f47e2a', variants: [
    { id: 'rose', color: '#e93562' },
    { id: 'violet', color: '#b640dd' },
    { id: 'soft', color: '#d3926c' },
    { id: 'muted', color: '#bf9a85' },
    { id: 'vivid', color: '#e86f00' },
    { id: 'deep', color: '#cd6100' },
    { id: 'bright', color: '#ffa26b' },
    { id: 'warm', color: '#e18e00' },
    { id: 'cool', color: '#fb745a' },
    { id: 'dawn', color: '#ff8591' },
  ] },
  { id: 'citrus', name: 'Citrus', file: '/themes/citrus.css', color: '#f69e00', variants: [
    { id: 'soft', color: '#dea868' },
    { id: 'muted', color: '#cdae8b' },
    { id: 'vivid', color: '#e59300' },
    { id: 'deep', color: '#cc8200' },
    { id: 'bright', color: '#ffc074' },
    { id: 'warm', color: '#ddac00' },
    { id: 'cool', color: '#ff954e' },
    { id: 'dawn', color: '#ffa691' },
    { id: 'dusk', color: '#aea600' },
    { id: 'pastel', color: '#f8cb97' },
  ] },
  { id: 'honey', name: 'Honey', file: '/themes/honey.css', color: '#d4a800', variants: [
    { id: 'soft', color: '#c4ac6b' },
    { id: 'muted', color: '#baad89' },
    { id: 'vivid', color: '#c59c00' },
    { id: 'deep', color: '#af8a00' },
    { id: 'bright', color: '#f0c12a' },
    { id: 'warm', color: '#b8b40b' },
    { id: 'cool', color: '#eb9a04' },
    { id: 'dawn', color: '#ffa05e' },
    { id: 'dusk', color: '#83ac29' },
    { id: 'pastel', color: '#e0cc98' },
  ] },
  { id: 'meadow', name: 'Meadow', file: '/themes/meadow.css', color: '#a8ad00', variants: [
    { id: 'soft', color: '#a6ab5a' },
    { id: 'muted', color: '#a5a97d' },
    { id: 'vivid', color: '#9ba000' },
    { id: 'deep', color: '#898d00' },
    { id: 'bright', color: '#c2c800' },
    { id: 'warm', color: '#7cba10' },
    { id: 'cool', color: '#c3a200' },
    { id: 'dawn', color: '#eaa000' },
    { id: 'dusk', color: '#05b047' },
    { id: 'pastel', color: '#c5ca89' },
  ] },
  { id: 'spring', name: 'Spring', file: '/themes/spring.css', color: '#6ab600', variants: [
    { id: 'soft', color: '#82ae61' },
    { id: 'muted', color: '#8ea87d' },
    { id: 'vivid', color: '#61a800' },
    { id: 'deep', color: '#559400' },
    { id: 'bright', color: '#7fd222' },
    { id: 'warm', color: '#00be5d' },
    { id: 'cool', color: '#9ca900' },
    { id: 'dawn', color: '#c6aa00' },
    { id: 'dusk', color: '#00a47f' },
    { id: 'pastel', color: '#a6cb8c' },
  ] },
  { id: 'forest', name: 'Forest', file: '/themes/forest.css', color: '#51cd85', variants: [
    { id: 'lime', color: '#84d24b' },
    { id: 'moss', color: '#a8c15c' },
    { id: 'soft', color: '#86c29a' },
    { id: 'muted', color: '#9abba4' },
    { id: 'vivid', color: '#00c470' },
    { id: 'deep', color: '#27ad67' },
    { id: 'bright', color: '#6ee89e' },
    { id: 'warm', color: '#00cfa8' },
    { id: 'cool', color: '#82c762' },
    { id: 'dawn', color: '#b4cb4e' },
  ] },
  { id: 'jade', name: 'Jade', file: '/themes/jade.css', color: '#00b28f', variants: [
    { id: 'soft', color: '#5ea992' },
    { id: 'muted', color: '#7aa295' },
    { id: 'vivid', color: '#00a483' },
    { id: 'deep', color: '#008f73' },
    { id: 'bright', color: '#00cfa6' },
    { id: 'warm', color: '#00afa8' },
    { id: 'cool', color: '#36b26c' },
    { id: 'dawn', color: '#78b955' },
    { id: 'dusk', color: '#0097a8' },
    { id: 'pastel', color: '#8ac6b2' },
  ] },
  { id: 'lagoon', name: 'Lagoon', file: '/themes/lagoon.css', color: '#00b6ac', variants: [
    { id: 'soft', color: '#62aea7' },
    { id: 'muted', color: '#7fa8a3' },
    { id: 'vivid', color: '#00a89f' },
    { id: 'deep', color: '#00948c' },
    { id: 'bright', color: '#00d3c7' },
    { id: 'warm', color: '#00b3c3' },
    { id: 'cool', color: '#00b991' },
    { id: 'dawn', color: '#5dc47e' },
    { id: 'dusk', color: '#009bc2' },
    { id: 'pastel', color: '#8ecbc5' },
  ] },
  { id: 'reef', name: 'Reef', file: '/themes/reef.css', color: '#00acb9', variants: [
    { id: 'soft', color: '#5fa6ad' },
    { id: 'muted', color: '#7aa0a4' },
    { id: 'vivid', color: '#009faa' },
    { id: 'deep', color: '#008b95' },
    { id: 'bright', color: '#00c8d7' },
    { id: 'warm', color: '#00a9cf' },
    { id: 'cool', color: '#00b0a3' },
    { id: 'dawn', color: '#37be95' },
    { id: 'dusk', color: '#248fcc' },
    { id: 'pastel', color: '#8ac3c9' },
  ] },
  { id: 'arctic', name: 'Arctic', file: '/themes/arctic.css', color: '#00b0d5', variants: [
    { id: 'soft', color: '#69a9be' },
    { id: 'muted', color: '#82a5b1' },
    { id: 'vivid', color: '#00a2c5' },
    { id: 'deep', color: '#008fad' },
    { id: 'bright', color: '#36caf1' },
    { id: 'warm', color: '#3fa9e5' },
    { id: 'cool', color: '#00b4be' },
    { id: 'dawn', color: '#0ac5b4' },
    { id: 'dusk', color: '#548dda' },
    { id: 'pastel', color: '#93c7d8' },
  ] },
  { id: 'azure', name: 'Azure', file: '/themes/azure.css', color: '#009bd6', variants: [
    { id: 'soft', color: '#5a97bb' },
    { id: 'muted', color: '#7394a9' },
    { id: 'vivid', color: '#008ec5' },
    { id: 'deep', color: '#007bab' },
    { id: 'bright', color: '#1bb5f8' },
    { id: 'warm', color: '#4492e7' },
    { id: 'cool', color: '#00a0bd' },
    { id: 'dawn', color: '#00b1b7' },
    { id: 'dusk', color: '#5d75d6' },
    { id: 'pastel', color: '#84b5d3' },
  ] },
  { id: 'denim', name: 'Denim', file: '/themes/denim.css', color: '#007dd6', variants: [
    { id: 'soft', color: '#4d7eb0' },
    { id: 'muted', color: '#627d9a' },
    { id: 'vivid', color: '#0071c3' },
    { id: 'deep', color: '#0060a6' },
    { id: 'bright', color: '#2896f5' },
    { id: 'warm', color: '#5071de' },
    { id: 'cool', color: '#0085b4' },
    { id: 'dawn', color: '#0096ae' },
    { id: 'dusk', color: '#6453c4' },
    { id: 'pastel', color: '#749cc6' },
  ] },
  { id: 'ocean', name: 'Ocean', file: '/themes/ocean.css', color: '#2f7fee', variants: [
    { id: 'teal', color: '#3be3d5' },
    { id: 'indigo', color: '#6235e9' },
    { id: 'soft', color: '#5b84bf' },
    { id: 'muted', color: '#6d84a6' },
    { id: 'vivid', color: '#0070ed' },
    { id: 'deep', color: '#0360cc' },
    { id: 'bright', color: '#549aff' },
    { id: 'warm', color: '#6772ee' },
    { id: 'cool', color: '#008bcc' },
    { id: 'dawn', color: '#009ec2' },
  ] },
  { id: 'midnight', name: 'Midnight', file: '/themes/midnight.css', color: '#6260ff', variants: [
    { id: 'soft', color: '#6a73c6' },
    { id: 'muted', color: '#7078a8' },
    { id: 'vivid', color: '#5749ff' },
    { id: 'deep', color: '#4a3bde' },
    { id: 'bright', color: '#7b84ff' },
    { id: 'warm', color: '#8b4ef3' },
    { id: 'cool', color: '#0071ff' },
    { id: 'dawn', color: '#0090d7' },
    { id: 'dusk', color: '#9726c6' },
    { id: 'pastel', color: '#8993da' },
  ] },
  { id: 'amethyst', name: 'Amethyst', file: '/themes/amethyst.css', color: '#8a5af4', variants: [
    { id: 'soft', color: '#8371c2' },
    { id: 'muted', color: '#8179a7' },
    { id: 'vivid', color: '#8335ff' },
    { id: 'deep', color: '#6e37d2' },
    { id: 'bright', color: '#9f7cff' },
    { id: 'warm', color: '#a94bde' },
    { id: 'cool', color: '#6069ff' },
    { id: 'dawn', color: '#2e89ff' },
    { id: 'dusk', color: '#ae26ab' },
    { id: 'pastel', color: '#a193d7' },
  ] },
  { id: 'orchid', name: 'Orchid', file: '/themes/orchid.css', color: '#b054f1', variants: [
    { id: 'soft', color: '#9e73c4' },
    { id: 'muted', color: '#967dac' },
    { id: 'vivid', color: '#ae10ff' },
    { id: 'deep', color: '#912fcf' },
    { id: 'bright', color: '#c479ff' },
    { id: 'warm', color: '#cb45d1' },
    { id: 'cool', color: '#8c67ff' },
    { id: 'dawn', color: '#718aff' },
    { id: 'dusk', color: '#cb1b98' },
    { id: 'pastel', color: '#ba96da' },
  ] },
  { id: 'berry', name: 'Berry', file: '/themes/berry.css', color: '#e12afb', variants: [
    { id: 'soft', color: '#c26ece' },
    { id: 'muted', color: '#b081b7' },
    { id: 'vivid', color: '#d400ee' },
    { id: 'deep', color: '#b900d0' },
    { id: 'bright', color: '#ec72ff' },
    { id: 'warm', color: '#fb00ca' },
    { id: 'cool', color: '#b367ff' },
    { id: 'dawn', color: '#9a8eff' },
    { id: 'dusk', color: '#e90081' },
    { id: 'pastel', color: '#db96e5' },
  ] },
  { id: 'blossom', name: 'Blossom', file: '/themes/blossom.css', color: '#e840c1', variants: [
    { id: 'soft', color: '#c670ad' },
    { id: 'muted', color: '#b280a2' },
    { id: 'vivid', color: '#e300ba' },
    { id: 'deep', color: '#c50ba1' },
    { id: 'bright', color: '#ff67d8' },
    { id: 'warm', color: '#f93494' },
    { id: 'cool', color: '#d14fe9' },
    { id: 'dawn', color: '#b77aff' },
    { id: 'dusk', color: '#ec0050' },
    { id: 'pastel', color: '#df96c8' },
  ] },
  { id: 'flamingo', name: 'Flamingo', file: '/themes/flamingo.css', color: '#ed4096', variants: [
    { id: 'soft', color: '#c86e93' },
    { id: 'muted', color: '#b27e91' },
    { id: 'vivid', color: '#e9008b' },
    { id: 'deep', color: '#c90f78' },
    { id: 'bright', color: '#ff6cae' },
    { id: 'warm', color: '#f73d68' },
    { id: 'cool', color: '#dd4abf' },
    { id: 'dawn', color: '#d363f0' },
    { id: 'dusk', color: '#e22a12' },
    { id: 'pastel', color: '#e094b1' },
  ] },
  { id: 'graphite', name: 'Graphite', file: '/themes/graphite.css', color: '#71717b', variants: [
    { id: 'ink', color: '#4b546f' },
    { id: 'pewter', color: '#648089' },
    { id: 'iron', color: '#6c6158' },
    { id: 'carbon', color: '#47474e' },
    { id: 'silver', color: '#919199' },
    { id: 'smoke', color: '#888393' },
    { id: 'ash', color: '#838173' },
    { id: 'charcoal', color: '#3a3a42' },
    { id: 'mineral', color: '#457274' },
    { id: 'umber', color: '#6c5147' },
  ] },
  { id: 'espresso', name: 'Espresso', file: '/themes/espresso.css', color: '#6f4c34', variants: [
    { id: 'soft', color: '#645144' },
    { id: 'muted', color: '#5e534b' },
    { id: 'vivid', color: '#6b3d1a' },
    { id: 'deep', color: '#52311a' },
    { id: 'bright', color: '#87634a' },
    { id: 'warm', color: '#6a502e' },
    { id: 'cool', color: '#72493d' },
    { id: 'dawn', color: '#7f5353' },
    { id: 'dusk', color: '#51441c' },
    { id: 'pastel', color: '#7f6e63' },
  ] },
  { id: 'sage', name: 'Sage', file: '/themes/sage.css', color: '#6c9173', variants: [
    { id: 'soft', color: '#798c7c' },
    { id: 'muted', color: '#7e8a80' },
    { id: 'vivid', color: '#568861' },
    { id: 'deep', color: '#507357' },
    { id: 'bright', color: '#84a98b' },
    { id: 'warm', color: '#62927f' },
    { id: 'cool', color: '#798e69' },
    { id: 'dawn', color: '#91976c' },
    { id: 'dusk', color: '#49807a' },
    { id: 'pastel', color: '#99aa9c' },
  ] },
  { id: 'plum', name: 'Plum', file: '/themes/plum.css', color: '#744c7d', variants: [
    { id: 'soft', color: '#6a556f' },
    { id: 'muted', color: '#655968' },
    { id: 'vivid', color: '#6f387b' },
    { id: 'deep', color: '#573160' },
    { id: 'bright', color: '#8c6395' },
    { id: 'warm', color: '#7e496f' },
    { id: 'cool', color: '#675188' },
    { id: 'dawn', color: '#63619b' },
    { id: 'dusk', color: '#72364f' },
    { id: 'pastel', color: '#85738a' },
  ] },
  { id: 'steel', name: 'Steel', file: '/themes/steel.css', color: '#597797', variants: [
    { id: 'soft', color: '#667688' },
    { id: 'muted', color: '#6c767f' },
    { id: 'vivid', color: '#436c96' },
    { id: 'deep', color: '#3e5b79' },
    { id: 'bright', color: '#718fb0' },
    { id: 'warm', color: '#657498' },
    { id: 'cool', color: '#4f7b92' },
    { id: 'dawn', color: '#548a96' },
    { id: 'dusk', color: '#605e84' },
    { id: 'pastel', color: '#8694a3' },
  ] },
]
